services:
  api:
    build: ./services/api
    ports: ["8000:8000"]
  web:
    build: ./web
    ports: ["3000:3000"]
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    depends_on: [api]
